### ISSUE TITLE
FomUserBundle - User listing - loading takes ages with many users

### ISSUE THREAD

**Issue by debugteam** [mapbender/fom#30]
In some projects (they got 1000+ users) the loading of the userslist was very slow (between 20 and 30 seconds).

My suggestion (and solution, since i've allready made a pull request for that issue) is to replace the current listing with jquery datatables (serverside implementation obviously) and only load a small amount of users at once.

Pull-Request: https://github.com/mapbender/fom/pull/29

**Comment by AxxL** [comment]
In hands of @LazerTiberius to provide this in his project. If finished it will flow back into Mapbender.
